# version: "3"
services:
    web:
        container_name: "portfolio-prod"

        build: .
        ports:
            - "8080:3001"

        env_file:
            - .env

        restart: "unless-stopped"
