FROM nginx AS nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ssl/ssl.cert /etc/ssl/ssl.cert
COPY ssl/ssl.key /etc/ssl/ssl.key

EXPOSE 80
EXPOSE 443

VOLUME /etc/nginx
VOLUME /etc/ssl
